### ISSUE TITLE
Loot range

### ISSUE THREAD

**Issue by Berringer** [capthehacker99/AutoLectern#17]
This is not really an issue, more a idea on what to add to the mod.
A magnet! I used this on my 120423451th shopping district and found it great! Does the trick!
Only thing I was having trouble with was when the lectern was not looted because of range. I know I could have had a stack of lecterns and it would be fine, but I did not at the time.
I had to /stop and then get the lectern and /start again. Sometimes it happened every time.
So, a new item that increases the loot range for lecterns or workstations would be great! 

I tried 2-3 different magnet mods but they did not work at all, unfortunately.
Thank you for this awesome mod!

**Comment by capthehacker99** [comment]
This is a client sided mod designed to be used on vanilla servers.
As such we cannot add magnets as that would have to be added on the server as well.
