### ISSUE TITLE
Autolectern not breaking lecterns

### ISSUE THREAD

**Issue by curllu** [capthehacker99/AutoLectern#21]
Autolectern breaks the lectern and works normally the first few times but then it gets stuck on breaking the lectern

**Comment by capthehacker99** [comment]
Which version are you using?
Can you send a video of this happening?

**Comment by curllu** [comment]
Im using 1.21 on feather client, here is a video of it happenign https://streamable.com/wilyu4

**Comment by capthehacker99** [comment]
You seem to be on a modified server and client.
Does it happen on single player and on vanilla client?

**Comment by curllu** [comment]
It works in singleplayer

**Comment by capthehacker99** [comment]
Do you know what server software is running where the problem occur?
You can see by joining the server and pressing F3 and looking at the top left

**Comment by curllu** [comment]
![Screenshot (118)](https://github.com/user-attachments/assets/282daf08-b291-4a98-9114-bd954cfb597d)

**Comment by curllu** [comment]
Server is hosted on pebble host

**Comment by curllu** [comment]
Just doesnt work on some servers ig

**Comment by capthehacker99** [comment]
Would be helpful if you could reproduce it on your own server so we can know why tf it doesn't work on some servers
