### ISSUE TITLE
no support for 1.19.2

### ISSUE THREAD

**Issue by TwoPointInfinity** [capthehacker99/AutoLectern#3]
game crashes on launch if on 1.19.2

**Comment by TwoPointInfinity** [comment]
also i wasnt sure if this mod was forge or fabric if you wanna add that to the readme

**Comment by TwoPointInfinity** [comment]
https://pastebin.com/4WBYe617 heres the log my bad

**Comment by capthehacker99** [comment]
Mojang changes `onSendCommand` making it crashes so I updated the mod.
[[1.19.2 Port]](https://github.com/capthehacker99/AutoLectern/releases/tag/1.19.2)
