### ISSUE TITLE
unsure of how to set min and max cost value

### ISSUE THREAD

**Issue by LifeBroGoo** [capthehacker99/AutoLectern#6]
also it stops after one break

**Comment by capthehacker99** [comment]
`/autolec add [enchant]? [(minLevel, maxLevel)/min/max/any] [(minPrice, maxPrice)/min/max/any]`

If you want max level protection with the range cost of between 0 and 32 emeralds it is:
`/autolec add minecraft:protection max 0 32`

Make sure you place the lectern in your off-hand slot, make sure you have more than 1 lectern.
If you don't have many lecterns turning sync item on may help:
`/autolec sync item`
